# Nginx image
FROM nginx:1.21.0

# removing default nginx.conf
RUN rm /etc/nginx/conf.d/*
RUN rm /etc/nginx/nginx.conf

# Copying our nginx.conf file
COPY nginx.conf /etc/nginx/
COPY default.conf /etc/nginx/conf.d/
EXPOSE 80 443


