# Generated by Django 4.2 on 2023-08-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_downloaded_saved',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('thumbnail_url', models.CharField(max_length=100, null=True)),
                ('video_link', models.CharField(max_length=1000, null=True)),
                ('playlist_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
