# Generated by Django 4.2 on 2023-07-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_app1', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Book',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=200)),
        #         ('author', models.CharField(max_length=100)),
        #         ('publication_date', models.DateField()),
        #         ('isbn', models.CharField(max_length=13)),
        #     ],
        # ),
        migrations.CreateModel(
            name='document_save',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='document/')),
            ],
        ),
        # migrations.CreateModel(
        #     name='user_info',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('first_name', models.CharField(max_length=200)),
        #         ('last_name', models.CharField(max_length=100)),
        #         ('dob', models.DateField()),
        #         ('status', models.CharField(max_length=100)),
        #     ],
        # ),
    ]
