# Generated by Django 4.2 on 2023-07-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app1', '0002_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Book',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=200)),
        #         ('author', models.CharField(max_length=100)),
        #         ('publication_date', models.DateField()),
        #         ('isbn', models.CharField(max_length=13)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='user_info',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('first_name', models.CharField(max_length=200)),
        #         ('last_name', models.CharField(max_length=100)),
        #         ('dob', models.DateField()),
        #         ('status', models.CharField(max_length=100)),
        #     ],
        # ),
        migrations.AddField(
            model_name='document_save',
            name='video_file',
            field=models.FileField(null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='document_save',
            name='document',
            field=models.FileField(null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='document_save',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
