# Generated by Django 4.2 on 2023-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app1', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='document/')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
