# Generated by Django 4.2 on 2023-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app1', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Save',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='document/')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
