# Generated by Django 4.2 on 2023-07-31 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app1', '0002_book_user_info'),
        ('data_app1', '0002_document'),
        ('data_app1', '0003_book_user_info_document_save_video_file_and_more'),
    ]

    operations = [
    ]
