# Generated by Django 4.2 on 2023-07-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app1', '0003_document_save_delete_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
