# Generated by Django 4.2 on 2023-07-31 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app1', '0002_book_user_info'),
        ('data_app1', '0003_book_user_info_document_save_video_file_and_more'),
        ('data_app1', '0003_document_save_delete_document 2'),
        ('data_app1', '0003_document_save_delete_document 3'),
        # ('data_app1', '0004_delete_document'),
    ]

    operations = [
    ]
